# Generated by Django 2.2.4 on 2019-09-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10)),
                ('uname', models.CharField(max_length=20)),
                ('uemail', models.EmailField(max_length=254)),
                ('ucontact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
