# Generated by Django 2.2.4 on 2019-10-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sendername', models.CharField(default='', max_length=20)),
                ('recievername', models.CharField(default='', max_length=20)),
                ('amount', models.FloatField(default='')),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'MoneyRequest',
                'unique_together': {('sendername', 'recievername')},
            },
        ),
    ]
