# Generated by Django 2.2.4 on 2019-09-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uTimelinePrivacy',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='uTransactionNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
