# Generated by Django 2.2.4 on 2019-10-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_auto_20190925_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uWalletBalance',
            field=models.FloatField(default=500.0),
        ),
    ]
