# Generated by Django 2.2.6 on 2019-10-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimelineApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='from_user_gender',
            field=models.BooleanField(default=True),
        ),
    ]
